<template>
    <LegalLayout title="Privacy policy" updated="31 August 2026">
        <section>
            <h2>Overview</h2>
            <p>
                MatchCalender provides live sports calendars you can subscribe
                to. This policy explains what data we collect when you use the
                site, why, and what we don't do. We built this product to be
                usable without an account, and we've kept data collection to the
                minimum that is required.
            </p>
        </section>

        <section>
            <h2>What we collect</h2>
            <ul>
                <li>
                    <strong>Your team/league/sport selections.</strong> When you
                    pick a team on the site, that choice is encoded directly
                    into the calendar link (URL) we generate for you and stored
                    in your browser's local storage so the site remembers your
                    last-viewed league. It is not tied to an account, an email
                    address, or anything that identifies you personally. We
                    don't know who you are.
                </li>
                <li>
                    <strong>A random ID in your calendar link.</strong> Every
                    link we generate ends with something like
                    <code>&amp;id=36wPQZ47d0pA</code>. It is 12 random
                    characters, generated by a random number generator with
                    nothing about you fed into it: not your name, email, IP
                    address, device, or location. Its only purpose is to let us
                    count how many calendar subscriptions are actually active,
                    which we cannot otherwise do: two people subscribing to the
                    same team send us identical requests, so without it they
                    are indistinguishable from one person.
                </li>
                <li>
                    <strong>Whether that link is still in use.</strong> Against
                    the random ID above, we store the team and leagues it was
                    created for, when it was created, when your calendar app
                    last fetched it, how many times it has, and which kind of
                    calendar app made the request (for example "Google
                    Calendar"). This tells us a subscription is alive; it tells
                    us nothing about who you are.
                </li>
                <li>
                    <strong>Standard server logs.</strong> Like virtually every
                    website, our servers record request logs (IP address,
                    timestamp, requested URL, user agent) for security and
                    debugging. These logs are kept only as long as needed to
                    operate the service and are not used for tracking,
                    advertising, or sold to anyone.
                </li>
                <li>
                    <strong>Calendar app requests.</strong> When your calendar
                    app (Google Calendar, Apple Calendar, Outlook, etc.)
                    refreshes your subscribed feed, it makes a request to our
                    server the same way your browser does. We use this only to
                    count active subscriptions as described above, and we don't
                    build a profile of you. The subscription record itself holds
                    no IP address; the separate server logs described above do
                    record one, as they do for every request to any website.
                </li>
                <li>
                    <strong>How long we keep it.</strong> A link that is
                    generated but never subscribed to is deleted automatically
                    after 7 days. Once subscribed, the record is deleted
                    automatically after 12 months with no fetch from your
                    calendar app, so unsubscribing erases it within a year
                    without you doing anything. Both run daily. You can also
                    ask us to remove it sooner. See "Your rights" below.
                </li>
                <li>
                    <strong>If you'd rather not be counted.</strong> The ID is
                    optional. Delete <code>&amp;id=…</code> from the end of your
                    calendar link before subscribing and the feed works exactly
                    the same. We simply won't know the subscription exists.
                </li>
            </ul>
        </section>

        <section>
            <h2>What we don't collect</h2>
            <ul>
                <li>No accounts, no passwords, no email addresses.</li>
                <li>No payment information. MatchCalender is free.</li>
                <li>
                    No advertising or third-party analytics/tracking scripts.
                </li>
                <li>
                    No cookies used for tracking (only your browser's own local
                    and session storage, on your device, to remember your
                    last-viewed league and the link you just generated).
                </li>
                <li>
                    No name, email address, IP address, device fingerprint or
                    location stored against your calendar link. The random ID
                    is not derived from any of them. We record only the family
                    of calendar app that fetched it, never the full browser or
                    device string it sends.
                </li>
            </ul>
        </section>

        <section>
            <h2>Third-party content</h2>
            <p>
                Team crests and league data are sourced from public sports data
                providers and league websites, and some team badge images are
                loaded directly from those third parties' own servers. Loading
                those images causes your browser to make a request to that third
                party, subject to their own privacy practices, the same way
                loading an image from any external site would. We don't control
                those providers' data practices.
            </p>
        </section>

        <section>
            <h2>Your rights</h2>
            <p>
                Because we don't collect personal data tied to an identity,
                there's generally nothing to access, export, or delete on
                request. If you've saved a calendar link somewhere and want it
                to stop working, you can simply unsubscribe from it in your
                calendar app. We don't need to be involved.
            </p>
        </section>

        <section>
            <h2>Changes to this policy</h2>
            <p>
                If our data practices change (for example, if we introduce
                optional accounts in the future), we'll update this page and
                change the "last updated" date above.
            </p>
        </section>

        <section>
            <h2>Contact</h2>
            <p>
                Questions about this policy? Email
                <a href="mailto:support@matchcalender.com"
                    >support@matchcalender.com</a
                >.
            </p>
        </section>
    </LegalLayout>
</template>

<script setup lang="ts">
import LegalLayout from "@/components/LegalLayout.vue";
</script>
